baseURL = 'http://astangamoni.cz/'
languageCode = 'cs'
title = 'Aštanga Yoga Monika Slabá'
theme = 'custom'
googleAnalytics = 'G-5PCK3188DQ'

[params]
  copyrightFrom = '2017'
  fixedNavBar = true
  listPageLinkText = "Rezervace"

[markup.goldmark.renderer]
  unsafe = true