baseURL = 'http://astangamoni.cz/'
languageCode = 'cs'
title = 'Aštanga jóga Monika Slabá'
theme = 'monika'
googleAnalytics = 'G-HBF67DF5L3'
summaryLength = 20

[params]
  copyrightFrom = '2017'
  fixedNavBar = true
  listPageLinkText = "Rezervace"

[markup.goldmark.renderer]
  unsafe = true
